# Generated by Django 2.1.4 on 2019-07-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myvideo',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
